### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by philwilliammee**
Compiling with laravel mix to reduce webpack dependencies. added linting, phpcs support also #2 added ability to disable any styling. Added drupal core dependencies for page loading and rendering. All around lots of good stuff. This is a breaking change and should be tagged with v2.0

### CODE REVIEW

**Comment by philwilliammee** [comment]
Hi Alison can you review this for me? probably just:
composer require and enable.
Then add a block to the page 
change some settings on the block save and make sure it renders?

**Comment by alisonjo2786** [comment]
Yes happy to! I'll take a look on Friday.

**Comment by philwilliammee** [comment]
> Yes happy to! I'll take a look on Friday.

Hi Alison,

actually hold off on this. I want to do some more clean up and testing first.

**Comment by alisonjo2786** [comment]
Hi Phil - okay!

**Comment by alisonjo2786** [comment]
Is the new `cwd_events_styling` block config option the reason it'll be a "breaking release" of the module, or is it the change in how the markup is rendered in `EventsBlock.php` (just at a glance I'm seeing that it doesn't use an inline `<script>` thingy), or both, or something else entirely?

**Comment by philwilliammee** [comment]
@alisonjo2786 I'm done working on it. If you want to review. I'll also put something in confluence blog post about it the changes once its merged.

Its more how the markup is rendered by `EventsBlock.php` . It no longer uses the scripting, it just creates a div. The render is now initiated by `drupal/core/jquery.once` which has been added as a package dependency. 

most sites can just upgrade by replacing the old source code with the new code and then opening the events block and saving it, then clear cache.

Also this isn't breaking but was a big improvement in this version:

-  it compiles differently. 
- The css and js are no longer bundled. 
- It supports a CSV of multiple departments ids like 'id1,id2,id3' 
- Also It has a lot of clean up, doc comments, and much cleaner source code.

for example code like this:
```javascript
    let time_hour = time.split(':')[0];
    let time_min = time.split(':')[1];
    if (parseInt(time_hour) >= 12) {
        if (parseInt(time_hour) > 12) {
            time_hour = (parseInt(time_hour) - 12);
        }
        return time_hour + ':' + time_min + ' p.m.';
    }
    else {
        return parseInt(time_hour) + ':' + time_min + ' a.m.';
    }
```

has been replaced with libraries to now look like this:

```js
    let eventTime = moment(dateTime).format('h:mm a');
```

**Comment by alisonjo2786** [comment]
@philwilliammee That sounds awesome, thank you!  I'm gonna poke around the interwebs a little and see if there might be a way to cover the block-saving-cache-clearing steps, and if not, no biggie -- that's what release notes are for! 😁 

(when you say "replacing the old source code with the new code," you mean the cwd_events module code, ya?  or something else?)

**Comment by philwilliammee** [comment]
@alisonjo2786 yeah I ment install /update new module/version. 

An option is you should be able to config synch the changes to the eventsBlock.

But I dont know if we can modify the eventsBlock config from within the module? 🤷‍♂  let me know if you have any ideas.

**Comment by philwilliammee** [comment]
@alisonjo2786 I went over the updates at the last dev meeting. It was all good. I've done a lot  of testing. I'm just going to deploy it. Thanks for your help!

**Pull request merged**
